- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml

- name: python setup
  ansible.builtin.import_role:
    name: common
    tasks_from: python.yaml
    
- name: system setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systems-setup.yaml