- name: copy rabbitmq repo
    ansible.builtin.copy:
     src: rabbitmq.repo
     dest: /etc/yum.repos.d/rabbitmq.repo

- name: install rabbitmq server
    ansible.builtin.package:
     name: rabbitmq-server
     state: present
 
- name: start and enable rabbitmq service
    ansible.builtin.service:
     name: rabbitmq-server
     state: started
     enabled: yes

- name: create and provide permission to user
    community.rabbitmq.rabbitmq_user:
     user: roboShop
     password: roboshop123
     permissions:
       - vhost: /
         configure_priv: .*
         read_priv: .*
         write_priv: .*
         state: present