- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml
  tags:
  - deployment
- name: nodejs setup
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs.yaml
  tags:
  - deployment  
- name: system setup
  ansible.builtin.import_role:
    name: common
    tasks_from: system-setup.yaml
  tags:
  - deployment